#ifndef PIXAQ_FISH_ART_H
#define PIXAQ_FISH_ART_H
// ---------------------------------------------------------------------------
// fish_art.h — the fish sprites, baked from the photo cut-outs in app/.
//
// Generated by tools/make_fish.py: the alpha the JPEG flattened onto a
// checkerboard is recovered, the fish is cropped and mirrored so the head sits
// at +x (what the strip renderer expects), then box-filtered down to sprite
// size. See the tool for how the matte is rebuilt.
// ---------------------------------------------------------------------------
#include <Arduino.h>

struct RGBA8 { uint8_t r, g, b, a; };

extern const RGBA8 NEON_ART[];      // 12 x 5
extern const RGBA8 GUPPY1_ART[];    // 24 x 13
extern const RGBA8 GUPPY2_ART[];    // 24 x 12
extern const RGBA8 GUPPY3_ART[];    // 24 x 12
extern const RGBA8 GUPPY4_ART[];    // 24 x 10
extern const RGBA8 GUPPY5_ART[];    // 24 x 13
extern const RGBA8 BLACK_ART[];     // 24 x 14
extern const RGBA8 CORY_ART[];      // 24 x 14
extern const RGBA8 SHRIMP_ART[];    // 24 x 8, body only - see make_fish.py
extern const RGBA8 EBIFRY_ART[];    // 24 x 9, the one that is not a photo

#endif // PIXAQ_FISH_ART_H
